name: Python Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Set Environment Variables
      run: |
        echo "FLASK_APP=app.app" >> $GITHUB_ENV
        echo "PYTHONPATH=$PYTHONPATH:./backend" >> $GITHUB_ENV

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt

    - name: Run database migrations
      working-directory: ./backend
      run: |
        flask db upgrade

    - name: Run tests
      working-directory: ./backend
      run: |
        pytest test/

    - name: Lint code
      run: |
        pip install flake8
        flake8 . --ignore E501,W503

    - name: Build Docker image
      run: |
        docker build . -t your_docker_image_name:latest

    - name: Deploy
      run: |
        echo "Deploying application..."


